=== fp-wemove/ingrid-mdek/ingrid-mdek-api/src/docs/igc_profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.portalu.de/igc-profile" xmlns="http://www.portalu.de/igc-profile">

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   
        ADAPT VERSION OF PROFILE FORMAT !
        - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <xs:attributeGroup name="attributes.profile">
        <xs:attribute name="version" type="xs:string" fixed="1.0.0"/>
    </xs:attributeGroup>
    

    <!-- ==============================
        elements 
        ============================== -->
    
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   
        profile
        - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <xs:element name="profile">
        <xs:complexType>
            <xs:all>
                <xs:element ref="name"/>
                <xs:element ref="fields"/>
                <xs:element ref="lists" minOccurs="0"/>
            </xs:all>
            <xs:attributeGroup ref="attributes.profile"/>
        </xs:complexType>
    </xs:element>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   
        complex elements
        - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <xs:element name="fields" type="Fields"/>
    <xs:element name="textField" type="TextField"/>
    <xs:element name="numberField" type="NumberField"/>    
    <xs:element name="dateField" type="DateField"/>
    <xs:element name="tableField" type="TableField"/>
    <xs:element name="legacyField" type="LegacyField"/>

    <xs:element name="lists" type="Lists"/>
    <xs:element name="sysList" type="SysList"/>
    
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   
        "simple" elements
        - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <xs:element name="name" type="xs:string"/>
    <xs:element name="id" type="xs:string"/>
    <xs:element name="localizedLabel" type="LocalizedString"/>
    <xs:element name="localizedLabelPostfix" type="LocalizedString"/>
    <xs:element name="localizedHelp" type="LocalizedString"/>
    <!-- script contains mapping to csw -->
    <xs:element name="scriptedCswMapping" type="xs:string"/>
    <!-- script contains validation (mandatory), visibility on INSPIRE themes etc. -->
    <xs:element name="scriptedProperties" type="xs:string"/>
    <!-- isVisible NOT scripted to be integrated in existing gui mechanism ("Katalogverwaltung/Feldeinstellungen") -->
    <xs:element name="isVisible" type="xs:boolean" default="true"/>
    <xs:element name="isIndexed" type="xs:boolean" default="true"/>
    <xs:element name="selectionListId" type="selectionListId"/>
    <xs:element name="layoutWidth" type="Percent" default="100"/>
    <xs:element name="layoutNumLines" type="xs:integer" default="1"/>
    <xs:element name="layoutCategory" type="xs:string"/>


    <!-- ==============================
        types 
        ============================== -->

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   
        element types
        - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- All possible fields in Profile -->
    <xs:complexType name="Fields">
        <xs:choice>
            <xs:element ref="textField"/>
            <xs:element ref="numberField"/>
            <xs:element ref="dateField"/>
            <xs:element ref="tableField"/>
            <xs:element ref="legacyField"/>
        </xs:choice>
    </xs:complexType>

    <!-- AbstractField: elements of all fields -->
    <xs:complexType name="AbstractField" abstract="true">
        <xs:sequence>
            <xs:element ref="id"/>
            <xs:element ref="isVisible" minOccurs="0"/>
            <xs:element ref="scriptedProperties" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- LegacyField: existing field in core model -->
    <xs:complexType name="LegacyField">
        <xs:complexContent>
            <xs:extension base="AbstractField"/>
        </xs:complexContent>
    </xs:complexType>

    <!-- AbstractNewField: additional elements of all new fields -->
    <xs:complexType name="AbstractNewField" abstract="true">
        <xs:complexContent>
            <xs:extension base="AbstractField">
                <xs:sequence>
                    <xs:element ref="localizedLabel" maxOccurs="unbounded"/>
                    <xs:element ref="localizedLabelPostfix" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="localizedHelp" maxOccurs="unbounded"/>
                    <xs:element ref="scriptedCswMapping"/>
                    <xs:element ref="isIndexed" minOccurs="0"/>
                    <xs:element ref="layoutWidth" minOccurs="0"/>
                    <xs:element ref="layoutCategory" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- TextField: new text field -->
    <xs:complexType name="TextField">
        <xs:complexContent>
            <xs:extension base="AbstractNewField">
                <xs:sequence>
                    <xs:element ref="layoutNumLines" minOccurs="0"/>
                    <xs:element ref="selectionListId" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!-- NumberField: new number field -->
    <xs:complexType name="NumberField">
        <xs:complexContent>
            <xs:extension base="AbstractNewField">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!-- DateField: new date field -->
    <xs:complexType name="DateField">
        <xs:complexContent>
            <xs:extension base="AbstractNewField">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- TableField: new table -->
    <xs:complexType name="TableField">
        <xs:complexContent>
            <xs:extension base="AbstractNewField">
                <xs:sequence>
                    <xs:element ref="layoutNumLines" minOccurs="0"/>
                    <xs:element name="columns" type="ColumnFields"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType> 
    <!-- ColumnFields: possible fields in columns -->
    <xs:complexType name="ColumnFields">
        <xs:choice>
            <xs:element ref="textField"/>
            <xs:element ref="numberField"/>
            <xs:element ref="dateField"/>
        </xs:choice>
    </xs:complexType>
    
    <!-- Defining / Redefining syslists (syslist exchange format !) -->
    <xs:complexType name="Lists">
        <xs:sequence>
            <xs:element ref="sysList" maxOccurs="unbounded"/>            
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SysList">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="entryIds">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="int" type="xs:integer" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="deEntries">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="string" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="enEntries" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="string" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="maintainable" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   
        "data" types
        - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- %: 0 - 100 -->
    <xs:simpleType name="Percent">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Lokalisierter String: STRING element mit lang-Attribut -->
    <xs:complexType name="LocalizedString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>     
        </xs:simpleContent>
    </xs:complexType>

    <!-- Auswahlliste: STRING element (= Listen-ID) mit "extendable"-Attribut (wenn freie EintrÃ¤ge) -->
    <xs:complexType name="selectionListId">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="extendable" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== fp-wemove/ingrid-mdek/ingrid-mdek-api/src/docs/igc_profile_instance0.xml
<?xml version="1.0" encoding="UTF-8"?>
<profile xmlns="http://www.portalu.de/igc-profile"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.portalu.de/igc-profile file:/C:/wemove/ingrid/dev/svn/ingrid-mdek/trunk/ingrid-mdek-api/src/docs/igc_profile.xsd" version="1.0.0">
    <name>name0</name>
    <fields>
        <textField>
                    <id>id0</id>
                    <isVisible>true</isVisible>
                    <scriptedProperties>scriptedProperties0</scriptedProperties>
                    <localizedLabel lang="lang1">localizedLabel0</localizedLabel>
                    <localizedLabel lang="lang3">localizedLabel1</localizedLabel>
                    <localizedLabelPostfix lang="lang5">localizedLabelPostfix0</localizedLabelPostfix>
                    <localizedHelp lang="lang7">localizedHelp0</localizedHelp>
                    <localizedHelp lang="lang9">localizedHelp1</localizedHelp>
                    <scriptedCswMapping>scriptedCswMapping0</scriptedCswMapping>
                    <isIndexed>true</isIndexed>
                    <layoutWidth>100</layoutWidth>
                    <layoutCategory>layoutCategory0</layoutCategory>
                <layoutNumLines>1</layoutNumLines>
                <selectionListId extendable="false">selectionListId0</selectionListId>
        </textField>
<!--        <numberField>
                <id>id1</id>
                <isVisible>true</isVisible>
                <scriptedProperties>scriptedProperties1</scriptedProperties>
                <localizedLabel lang="lang11">localizedLabel2</localizedLabel>
                <localizedLabel lang="lang13">localizedLabel3</localizedLabel>
                <localizedLabelPostfix lang="lang15">localizedLabelPostfix1</localizedLabelPostfix>
                <localizedHelp lang="lang17">localizedHelp2</localizedHelp>
                <localizedHelp lang="lang19">localizedHelp3</localizedHelp>
                <scriptedCswMapping>scriptedCswMapping1</scriptedCswMapping>
                <isIndexed>true</isIndexed>
                <layoutWidth>100</layoutWidth>
                <layoutCategory>layoutCategory1</layoutCategory>
        </numberField>-->
<!--        <dateField>
                <id>id2</id>
                <isVisible>true</isVisible>
                <scriptedProperties>scriptedProperties2</scriptedProperties>
                <localizedLabel lang="lang21">localizedLabel4</localizedLabel>
                <localizedLabel lang="lang23">localizedLabel5</localizedLabel>
                <localizedLabelPostfix lang="lang25">localizedLabelPostfix2</localizedLabelPostfix>
                <localizedHelp lang="lang27">localizedHelp4</localizedHelp>
                <localizedHelp lang="lang29">localizedHelp5</localizedHelp>
                <scriptedCswMapping>scriptedCswMapping2</scriptedCswMapping>
                <isIndexed>true</isIndexed>
                <layoutWidth>100</layoutWidth>
                <layoutCategory>layoutCategory2</layoutCategory>
        </dateField>-->
<!--        <tableField>
                    <id>id3</id>
                    <isVisible>true</isVisible>
                    <scriptedProperties>scriptedProperties3</scriptedProperties>
                    <localizedLabel lang="lang31">localizedLabel6</localizedLabel>
                    <localizedLabel lang="lang33">localizedLabel7</localizedLabel>
                    <localizedLabelPostfix lang="lang35">localizedLabelPostfix3</localizedLabelPostfix>
                    <localizedHelp lang="lang37">localizedHelp6</localizedHelp>
                    <localizedHelp lang="lang39">localizedHelp7</localizedHelp>
                    <scriptedCswMapping>scriptedCswMapping3</scriptedCswMapping>
                    <isIndexed>true</isIndexed>
                    <layoutWidth>100</layoutWidth>
                    <layoutCategory>layoutCategory3</layoutCategory>
                <layoutNumLines>1</layoutNumLines>
                <columns>
                    <textField>
                                <id>id4</id>
                                <isVisible>true</isVisible>
                                <scriptedProperties>scriptedProperties4</scriptedProperties>
                                <localizedLabel lang="lang41">localizedLabel8</localizedLabel>
                                <localizedLabel lang="lang43">localizedLabel9</localizedLabel>
                                <localizedLabelPostfix lang="lang45">localizedLabelPostfix4</localizedLabelPostfix>
                                <localizedHelp lang="lang47">localizedHelp8</localizedHelp>
                                <localizedHelp lang="lang49">localizedHelp9</localizedHelp>
                                <scriptedCswMapping>scriptedCswMapping4</scriptedCswMapping>
                                <isIndexed>true</isIndexed>
                                <layoutWidth>100</layoutWidth>
                                <layoutCategory>layoutCategory4</layoutCategory>
                            <layoutNumLines>1</layoutNumLines>
                            <selectionListId extendable="false">selectionListId1</selectionListId>
                    </textField>
<!--                    <numberField>
                            <id>id5</id>
                            <isVisible>true</isVisible>
                            <scriptedProperties>scriptedProperties5</scriptedProperties>
                            <localizedLabel lang="lang51">localizedLabel10</localizedLabel>
                            <localizedLabel lang="lang53">localizedLabel11</localizedLabel>
                            <localizedLabelPostfix lang="lang55">localizedLabelPostfix5</localizedLabelPostfix>
                            <localizedHelp lang="lang57">localizedHelp10</localizedHelp>
                            <localizedHelp lang="lang59">localizedHelp11</localizedHelp>
                            <scriptedCswMapping>scriptedCswMapping5</scriptedCswMapping>
                            <isIndexed>true</isIndexed>
                            <layoutWidth>100</layoutWidth>
                            <layoutCategory>layoutCategory5</layoutCategory>
                    </numberField>-->
<!--                    <dateField>
                            <id>id6</id>
                            <isVisible>true</isVisible>
                            <scriptedProperties>scriptedProperties6</scriptedProperties>
                            <localizedLabel lang="lang61">localizedLabel12</localizedLabel>
                            <localizedLabel lang="lang63">localizedLabel13</localizedLabel>
                            <localizedLabelPostfix lang="lang65">localizedLabelPostfix6</localizedLabelPostfix>
                            <localizedHelp lang="lang67">localizedHelp12</localizedHelp>
                            <localizedHelp lang="lang69">localizedHelp13</localizedHelp>
                            <scriptedCswMapping>scriptedCswMapping6</scriptedCswMapping>
                            <isIndexed>true</isIndexed>
                            <layoutWidth>100</layoutWidth>
                            <layoutCategory>layoutCategory6</layoutCategory>
                    </dateField>-->
                </columns>
        </tableField>-->
<!--        <legacyField>
            <id>id7</id>
            <isVisible>true</isVisible>
            <scriptedProperties>scriptedProperties7</scriptedProperties>
        </legacyField>-->
    </fields>
</profile>
